version: '3.3'

services:
  node:
    build:
      context: ./node
      args:
        - NODE_VERSION=latest
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=production
        - YARN=false
    volumes:
      - .:/opt/app
    entrypoint: run-nodock "node index.js"
    tty: true
    ports:
      - 3000:3000

  mariaDB:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: muzmatch
      MYSQL_PASSWORD: muzmatch
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stringdb
    ports:
      - "3306:3306"

  redis:
    build:
      context: ./redis
    ports:
      - "6379"
    volumes:
      - ./redisBackup/redis:/data


